-- =========================
-- Natural Targets Seed (UPSERT)
-- =========================
-- NOTE:
-- - 운영/공유 DB에서 안전하게 반복 실행할 수 있도록 DELETE 없이 UPSERT로만 동작합니다.
-- - slug는 시스템 내 식별자이므로 변경하지 않는 것을 권장합니다.

INSERT INTO natural_targets (slug, display_name, description)
VALUES
  -- 비정상 신호조절 (abnormal_signals) - 비정상 세포 신호/경로
  ('hedgehog', 'Hedgehog signaling', '여러 암에서 보고되는 비정상 신호 경로로 언급됨'),
  ('wnt_beta_catenin', 'Wnt/β-catenin', '암 관련 비정상 신호 경로로 언급됨'),
  ('notch', 'Notch signaling', '일부 암과 연관된 신호 경로로 언급됨'),
  ('stat3', 'STAT3', '염증성 사이토카인/ TLR 자극에 의해 활성화될 수 있는 전사인자로 언급됨'),
  ('nfkb', 'NF-κB', '니클로사마이드가 타겟한다고 언급된 신호/전사인자'),
  ('ras', 'RAS', '일부 암에서 의존성이 있으며 macropinocytosis와 연관된 유전자 계열로 언급됨'),
  ('akt', 'AKT', 'STAT3 신호 이후 과발현 예시로 언급됨'),
  ('cmyc', 'c-Myc', 'Wnt/Notch 관련 및 대사/공격성 연관 유전자로 언급됨'),
  ('cyclin_d1', 'Cyclin D1', 'Wnt/β-catenin 경로 영향 하에 과발현될 수 있는 단백질로 언급됨'),
  ('mir_34a', 'miR-34a', 'Wnt/β-catenin 신호를 컨트롤하는 후생적 마이크로RNA로 언급됨'),

  -- 비정상 신호조절 (abnormal_signals) - 수용체/표면 분자
  ('integrins', 'Integrins', '세포 부착 관련 표면 분자로 전이/혈류 이동과 연관 가능하다고 언급됨'),
  ('estrogen_receptor', 'Estrogen receptor (ER)', '유방암/난소암/자궁내막암 등에서 상향조절 가능 수용체로 언급됨'),
  ('egfr', 'EGFR', '상피성장인자수용체로 천연물(예: EGCG/커큐민/버버린)과 연관 언급됨'),
  ('her2', 'HER2', 'EGFR 계열로 chloroquine 관련 내성 맥락에서 언급됨'),

  -- 비정상 신호조절 (abnormal_signals) - 침윤/혈관신생/저산소 반응
  ('mmp2', 'MMP-2', '세포외기질 분해 관련 MMP로 언급됨'),
  ('mmp3', 'MMP-3', '세포외기질 분해 관련 MMP로 언급됨'),
  ('mmp9', 'MMP-9', '세포외기질 분해 관련 MMP로 언급됨'),
  ('vegf', 'VEGF', '혈관신생 관련 성장인자로 언급됨'),
  ('pdgf', 'PDGF', '성장인자(미세환경) 축으로 언급됨'),
  ('hif', 'HIF (Hypoxia-inducible factor)', '저산소에서 활성화되어 VEGF 증가에 관여한다고 언급됨'),


  -- 면역 균형 (immune_balance) - 선천면역/염증 축
  ('tlr4', 'TLR4', '암에서 활성화되어 있을 수 있는 Toll-like receptor로 언급됨'),
  ('tlr9', 'TLR9', '종양발생 바이러스/진행암과 연관 가능 표적으로 언급됨'),
  ('il1', 'Interleukin-1 (IL-1)', '염증성 사이토카인으로 COX/PGE2 축과 연관되어 언급됨'),
  ('il6', 'Interleukin-6 (IL-6)', '지속적 노출이 암 관련 신호를 촉발할 수 있는 염증성 사이토카인으로 언급됨'),
  ('cox', 'COX (Cyclo-oxygenase)', '염증성 사이토카인에 의해 관련되며 NSAID로 중화 가능하다고 언급됨'),
  ('pge2', 'PGE2', '염증성 프로스타글란딘으로 면역억제/염증 축에서 언급됨'),
  ('tgfb', 'TGF-β', '면역억제 및 종양 미세환경 재편에 관여하는 사이토카인으로 언급됨'),
  ('il10', 'Interleukin-10 (IL-10)', '대표적인 면역억제성 사이토카인으로 언급됨'),
  ('ido', 'Indoleamine 2,3-dioxygenase (IDO)', '트립토판 대사를 통해 면역억제 환경 형성에 관여하는 축으로 언급됨'),
  ('ido1', 'Indoleamine 2,3-dioxygenase 1 (IDO1)', '트립토판 대사 기반 면역억제 효소로 언급됨'),
  ('ifng', 'Interferon-γ (IFN-γ)', '항암 면역 활성과 연관되는 면역 자극 사이토카인으로 언급됨'),
  ('il2', 'Interleukin-2 (IL-2)', 'T세포 활성과 증식에 관여하는 면역 조절 사이토카인으로 언급됨'),
  ('ccr5', 'CCR5', '면역세포 이동과 종양 미세환경 신호에 관여하는 케모카인 수용체로 언급됨'),
  ('pd1', 'PD-1', '대표적인 면역관문 수용체로 언급됨'),
  ('pdl1', 'PD-L1', '종양의 면역회피와 관련된 면역관문 리간드로 언급됨'),
  ('ctla4', 'CTLA-4', 'T세포 억제성 면역관문으로 언급됨'),
  ('ox40', 'OX40', 'T세포 활성화와 면역 증폭에 관여하는 공자극 수용체로 언급됨'),
  ('treg', 'Regulatory T cells (Treg)', '면역억제적 T세포 집단으로 언급됨'),
  ('mdsc', 'Myeloid-derived suppressor cells (MDSC)', '면역억제성 골수유래 세포 집단으로 언급됨'),
  ('tams', 'Tumor-associated macrophages (TAMs)', '종양 친화적 면역 미세환경과 연관된 대식세포 집단으로 언급됨'),
  ('m2_macrophage', 'M2 macrophage', '면역억제 및 조직재형성과 연관된 대식세포 표현형으로 언급됨'),
  ('sting', 'STING pathway', '선천면역 활성과 인터페론 반응에 관여하는 경로로 언급됨'),
  ('nk_cells', 'Natural killer cells', '선천적 항암 면역에 관여하는 세포 집단으로 언급됨'),
  ('th1', 'T helper 1 (Th1)', '세포성 면역과 항암 면역 반응 쪽으로 기울어진 보조 T세포 축으로 언급됨'),
  ('th2', 'T helper 2 (Th2)', '체액성 면역 및 면역 균형 전환과 연관된 보조 T세포 축으로 언급됨'),
  ('microbiome', 'Microbiome', '면역 훈련과 전신 염증 상태에 영향을 주는 미생물 생태계로 언급됨'),
  ('gut_microbiome', 'Gut microbiome', '장내 면역 균형과 치료 반응성에 영향을 주는 미생물군으로 언급됨'),
  ('acidic_tumor_microenvironment', 'Acidic tumor microenvironment', '면역세포 기능을 저해할 수 있는 산성 종양 미세환경으로 언급됨'),
  ('cox2', 'COX-2', '면역억제성 염증 및 PGE2 생성과 연관된 효소로 언급됨'),
  ('arginase', 'Arginase', '아르기닌 대사를 통해 T세포 기능 억제와 연관되는 효소로 언급됨'),
  ('complement_c4_function', 'Complement C4 function', '보체계 활성과 선천면역 반응 조절에 관여하는 기능 축으로 언급됨'),
  ('neutrophil_function', 'Neutrophil function', '호중구 기반 선천면역 반응성과 염증 조절에 관여하는 기능 축으로 언급됨'),


  -- 대사 안정화 (metabolic_stability) - 포도당/해당 및 관련 대사
  ('insulin', 'Insulin', '대사/성장 신호에서 중요한 호르몬으로 언급됨'),
  ('glut1', 'GLUT1', '암세포에서 포도당 흡수 증가와 관련된 수송체로 언급됨'),
  ('aerobic_glycolysis', 'Aerobic glycolysis', '와버그 효과 관련 포도당 대사 경로로 언급됨'),
  ('pppathway', 'Pentose phosphate pathway (PPP)', '오탄당 인산 경로로 언급됨'),
  ('hexokinase2', 'Hexokinase 2 (HK2)', '메트포민이 억제 가능하다고 언급된 해당계 효소'),
  ('oxphos', 'Oxidative phosphorylation (OXPHOS)', '산화적 인산화 경로로 언급됨'),
  ('complex1', 'Mitochondrial Complex I', '메트포민이 기능을 억제한다고 언급됨'),
  ('pdh', 'Pyruvate dehydrogenase (PDH)', 'DCA가 활성화한다고 언급된 미토콘드리아 포도당 산화 관련 효소'),
  ('pdk', 'Pyruvate dehydrogenase kinase (PDK)', 'DCA가 억제한다고 언급된 PDH 조절 효소'),
  ('ampk', 'AMPK', 'mTOR를 낮추는 방향의 대사 조절 효소로 언급됨'),
  ('ldha', 'Lactate dehydrogenase A (LDHA)', '피루브산을 젖산으로 전환하는 해당계 말단 효소로 언급됨'),
  ('lactate', 'Lactate', '종양 미세환경 산성화와 대사 재프로그래밍에 연관된 대사산물로 언급됨'),
  ('acetyl_coa', 'Acetyl-CoA', '에너지 생산과 지질 생합성의 중심 대사 노드로 언급됨'),
  ('mct1', 'Monocarboxylate transporter 1 (MCT1)', '젖산 등 모노카복실산 수송에 관여하는 수송체로 언급됨'),
  ('mct4', 'Monocarboxylate transporter 4 (MCT4)', '고해당성 세포의 젖산 배출과 연관된 수송체로 언급됨'),
  ('g6pd', 'Glucose-6-phosphate dehydrogenase (G6PD)', '오탄당 인산 경로의 핵심 효소로 언급됨'),

  -- 대사 안정화 (metabolic_stability) - 지질/콜레스테롤/지방산 축
  ('srebp1', 'SREBP-1', '지방산 합성 조절 축으로 언급됨'),
  ('srebp2', 'SREBP-2', '콜레스테롤/메발론산 경로 조절 축으로 언급됨'),
  ('acly', 'ACLY', 'ATP 시트르산 분해효소로 지방 대사 축에서 언급됨'),
  ('fas', 'FAS (Fatty acid synthesis)', '지방산 합성 경로로 언급됨'),
  ('fasn', 'Fatty acid synthase (FASN)', '지방산 합성의 핵심 효소로 언급됨'),
  ('mevalonate', 'Mevalonate pathway', '콜레스테롤 합성/막 생성 관련 경로로 언급됨'),
  ('hmgcr', 'HMG-CoA reductase (HMGCR)', '메발론산 경로의 속도결정 효소로 언급됨'),
  ('fao', 'Fatty acid oxidation (FAO)', '일부 내성/줄기세포 관련 암에서 항진될 수 있는 경로로 언급됨'),
  ('cpt1', 'Carnitine palmitoyltransferase 1 (CPT1)', '지방산 산화 유입 단계의 핵심 효소로 언급됨'),
  ('ldlr', 'LDL receptor (LDLR)', '암이 LDL 획득을 위해 수용체를 늘린다고 언급됨'),
  ('acss2', 'Acetyl-CoA synthetase 2 (ACSS2)', 'acetate를 acetyl-CoA로 전환하는 효소로 언급됨'),
  ('acetate-srebp-1', 'Acetate-SREBP-1', '지방산 합성 조절 축으로 언급됨'),
  ('mevalonate-srebp-2', 'Mevalonate-SREBP-2', '콜레스테롤/메발론산 경로 조절 축으로 언급됨'),


  -- 대사 안정화 (metabolic_stability) - 아미노산/자가포식/핵산 재활용
  ('igf1', 'IGF-1', '인슐린 유사 성장인자로 차단이 중요하다고 언급됨'),
  ('mtor', 'mTOR', 'AMPK와 연관된 주요 대사 조절 축으로 언급됨'),
  ('glutaminolysis', 'Glutaminolysis', '공격적 암/전이암에서 활성화될 수 있는 글루타민 대사로 언급됨'),
  ('glutamine_transport', 'Glutamine transport', '글루타민 흡수(수송) 축이 표적이 될 수 있다고 언급됨'),
  ('glutaminase', 'Glutaminase', '글루타민 분해 관련 효소 억제 축(억제제)로 언급됨'),
  ('gls', 'Glutaminase (GLS)', '글루타민을 글루탐산으로 전환하는 효소로 언급됨'),
  ('asct2', 'Alanine serine cysteine transporter 2 (ASCT2)', '글루타민 유입과 연관된 대표적 수송체로 언급됨'),
  ('gdh_kgdh', 'GDH/KGDH', 'Glutamate dehydrogenase / Ketoglutarate dehydrogenase 축으로 언급됨'),
  ('autophagy_nucleoside_salvage', 'Nucleoside salvage (autophagy)', '핵산 분해물질 재사용/자가포식 맥락의 표적으로 언급됨'),
  ('macropinocytosis', 'Macropinocytosis', '영양부족 환경에서 세포외 단백질/지방 흡수 경로로 언급됨'),
  ('nucleoside_salvage', 'Nucleoside salvage', '핵산 분해물질 재사용/자가포식 맥락의 표적으로 언급됨'),
  ('gln_oxphos', 'Gln OXPHOS', '글루타민 대사 경로로 언급됨'),

  -- 비정상 신호조절 (abnormal_signals) - 성장/호르몬/혈관신생 스위치
  ('jak2', 'JAK2', '사이토카인 신호 전달과 성장 관련 경로에 관여하는 키나아제로 언급됨'),
  ('pi3k', 'PI3K', '생존과 성장 신호를 매개하는 주요 세포 신호 경로로 언급됨'),
  ('beta_catenin', 'β-catenin', 'Wnt 신호와 전사 활성화에 관여하는 핵심 인자로 언급됨'),
  ('sonic_hedgehog', 'Sonic Hedgehog (SHH)', 'Hedgehog 계열의 성장 신호 리간드로 언급됨'),
  ('bfgf', 'Basic fibroblast growth factor (bFGF)', '혈관신생 및 성장 자극과 연관된 성장인자로 언급됨'),
  ('fgf', 'Fibroblast growth factor (FGF)', '세포 성장과 분화, 혈관신생과 연관된 성장인자로 언급됨'),
  ('fgfr', 'Fibroblast growth factor receptor (FGFR)', 'FGF 신호를 전달하는 수용체로 언급됨'),
  ('emt', 'Epithelial-mesenchymal transition (EMT)', '침윤성과 전이성 증가와 연관된 표현형 전환으로 언급됨'),
  ('angiogenesis', 'Angiogenesis', '종양 혈관신생과 연관된 과정으로 언급됨'),
  ('progesterone_receptor', 'Progesterone receptor (PR)', '호르몬 반응성과 연관된 핵수용체로 언급됨'),
  ('androgen_receptor', 'Androgen receptor (AR)', '호르몬 의존성 성장 신호와 연관된 핵수용체로 언급됨'),

  -- 신경·스트레스 (neuro_stress) - 자율신경/호르몬/리듬 축
  ('beta_adrenergic_receptor', 'Beta-adrenergic receptor', '교감신경성 신호 전달과 연관된 수용체로 언급됨'),
  ('beta2_adrenergic_receptor', 'Beta-2 adrenergic receptor', '스트레스 호르몬 반응과 연관된 베타 아드레날린 수용체로 언급됨'),
  ('epinephrine', 'Epinephrine', '급성 스트레스 반응에 관여하는 카테콜아민으로 언급됨'),
  ('norepinephrine', 'Norepinephrine', '교감신경 활성과 연관된 대표적 카테콜아민으로 언급됨'),
  ('cortisol', 'Cortisol', '만성 스트레스와 HPA 축 반응의 대표적 호르몬으로 언급됨'),
  ('glucocorticoid_receptor', 'Glucocorticoid receptor (GR)', '코르티솔 신호를 매개하는 핵수용체로 언급됨'),
  ('hpa_axis', 'Hypothalamic-pituitary-adrenal axis (HPA axis)', '스트레스 호르몬 조절의 핵심 축으로 언급됨'),
  ('autonomic_nervous_system', 'Autonomic nervous system', '교감·부교감 균형을 포함하는 자율신경계로 언급됨'),
  ('sympathetic_tone', 'Sympathetic tone', '교감신경 항진 정도를 나타내는 상태 지표로 언급됨'),
  ('parasympathetic_tone', 'Parasympathetic tone', '회복과 이완을 담당하는 부교감신경 활성 지표로 언급됨'),
  ('hrv', 'Heart rate variability (HRV)', '자율신경 균형과 회복 탄력성을 반영하는 지표로 언급됨'),
  ('circadian_rhythm', 'Circadian rhythm', '일주기 리듬과 수면-각성 조절 축으로 언급됨'),
  ('melatonin', 'Melatonin', '수면 및 일주기 신호와 연관된 호르몬으로 언급됨'),

  -- 회복증진 (recovery) - 산화 스트레스/세포사멸 축
  ('ros', 'ROS', '활성산소종으로 세포사멸 민감도 조절 축에서 언급됨'),
  ('glutathione', 'Glutathione (GSH)', '항산화 상태/세포사멸 민감도에 관여하는 축으로 언급됨'),
  ('caspases', 'Caspases', '프로그램된 세포사멸(아포토시스)에서 핵심 효소군으로 언급됨'),
  ('bcl2_bax', 'Bcl-2/Bax', '세포사멸 조절 축으로 언급됨'),
  ('fas_receptor', 'Fas (death receptor)', '세포 표면 사멸 수용체로 카스파제 8 촉발과 연관되어 언급됨'),
  ('caspase3', 'Caspase-3', 'chloroquine 및 일부 물질과 연관되어 언급된 세포사멸 실행 카스파제'),
  ('dnmt', 'DNA methyltransferase (DNMT)', 'DNA 메틸화와 후성유전 조절에 관여하는 효소군으로 언급됨'),
  ('dnmt1', 'DNA methyltransferase 1 (DNMT1)', '유지 메틸화에 관여하는 대표적 DNA 메틸전달효소로 언급됨'),
  ('dnmt3a', 'DNA methyltransferase 3A (DNMT3A)', 'de novo DNA 메틸화에 관여하는 효소로 언급됨'),
  ('dnmt3b', 'DNA methyltransferase 3B (DNMT3B)', 'de novo DNA 메틸화에 관여하는 효소로 언급됨'),
  ('tet', 'Ten-eleven translocation (TET)', 'DNA 탈메틸화와 후성유전 재조정에 관여하는 효소군으로 언급됨'),
  ('hdac', 'Histone deacetylase (HDAC)', '히스톤 탈아세틸화 기반 후성유전 조절 효소군으로 언급됨'),
  ('hats', 'Histone acetyltransferases (HATs)', '히스톤 아세틸화 기반 전사 조절 효소군으로 언급됨'),
  ('histone_acetylation', 'Histone acetylation', '염색질 개방성과 전사 활성 조절에 연관된 후성유전 표지로 언급됨'),
  ('dna_methylation', 'DNA methylation', '유전자 발현 억제와 연관된 대표적 후성유전 조절 기전으로 언급됨'),
  ('mitochondria', 'Mitochondria', '에너지 생산과 세포사멸 신호를 함께 조절하는 세포소기관으로 언급됨'),
  ('mitochondrial_function', 'Mitochondrial function', '미토콘드리아의 에너지 생산 및 회복 기능 전반을 가리키는 축으로 언급됨'),
  ('redox', 'Redox balance', '산화-환원 균형과 세포 스트레스 적응 상태를 반영하는 축으로 언급됨'),
  ('nrf2', 'NRF2', '항산화 반응과 해독 유전자 조절에 관여하는 전사인자로 언급됨'),
  ('thioredoxin', 'Thioredoxin', '세포 내 산화환원 조절에 관여하는 항산화 단백질 시스템으로 언급됨'),
  ('gpx', 'Glutathione peroxidase (GPx)', '과산화물 제거와 항산화 방어에 관여하는 효소로 언급됨'),
  ('catalase', 'Catalase', '과산화수소 제거와 항산화 방어에 관여하는 효소로 언급됨'),
  ('sod', 'Superoxide dismutase (SOD)', '초과산화물 제거와 산화스트레스 완화에 관여하는 효소로 언급됨'),
  ('nadph', 'NADPH', '항산화 방어와 생합성 대사의 환원력 공급원으로 언급됨'),
  ('oxidative_stress', 'Oxidative stress', '활성산소에 의한 손상 및 적응 상태를 설명하는 축으로 언급됨'),
  ('cytochrome_c', 'Cytochrome c', '미토콘드리아 유래 세포사멸 신호 전달에 관여하는 단백질로 언급됨'),
  ('bax', 'BAX', '미토콘드리아 경로 세포사멸 촉진 단백질로 언급됨'),
  ('bad', 'BAD', '세포사멸 촉진과 BCL-2 계열 조절에 관여하는 단백질로 언급됨'),
  ('bak', 'BAK', '미토콘드리아 외막 투과성과 연관된 세포사멸 촉진 단백질로 언급됨'),
  ('bclxl', 'Bcl-xL', '항세포사멸 기능을 가진 BCL-2 계열 단백질로 언급됨'),
  ('apoptosis', 'Apoptosis', '손상 세포를 프로그램된 방식으로 제거하는 세포사멸 과정으로 언급됨'),
  ('caspase8', 'Caspase-8', 'death receptor 경로와 연관된 개시 카스파제로 언급됨'),
  ('caspase9', 'Caspase-9', '미토콘드리아 경로와 연관된 개시 카스파제로 언급됨'),
  ('p53', 'p53', '손상 반응, 세포주기 정지, 세포사멸 유도와 연관된 종양억제 인자로 언급됨'),
  ('ascorbate_recycling', 'Ascorbate recycling', '비타민 C 재생과 항산화 완충 능력 유지에 관여하는 회복 축으로 언급됨')
ON CONFLICT (slug) DO UPDATE
SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description;
